apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: eehub-infra
