---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  encryptedData:
    api-token: AgAoKtHpEUS6it8QBQIL3t5149T0Gd5/4iJeCO7kfo8Snhgx8y4lOPOEs5T09/KWF5/rzA0MIw6FgsNyH4fDQhDmx9nMFqbY54lGoYY36vPqy0yMFBcfnq3DJqp7T3IYoRQFz4rM3QHzzz3s7xVferdZwufpXyZPfBd+B4StBsoPC/w3ZaoLsWVQNDQShwkbU1tulcRgTRoyrl5lJpDr95Nf4HYbFe/RZSzIJpLCU1sXPPw5rm1DUxlBvnKyicg1JV7bTHUZcQ1n5KbCCDf/3VMRVyPBARsLucWF105E8mbCrLTPICpHZ9Rxt2MifsgRaVfaJfxAP8lHxZjkwth+AtyNqePfrHkTLvJb+SsaIjcBlYW9ztkup8qsAkDJiylUvTuCMm1ez+8BYFRoJ4VZm5OtAbaP7NCkMAXeQyii1/5omiIvUzRgI3osoxnfiisA7JuKKtLiD5Gq62nY34mMlPeHkaWPlJz3pr/rsGysPlhP1ifmxrjlol/S1/WN5D6DrDuEbWwc/f2HHE/DvLpufmAchphiSWHoEGZx83D8gCTnQXFvR0wD6z5suMpo6HIxHDDmd+ET3SUkCWXCry2gvfXVi32NSMEGwIK1epEXTkoGGcWo6p01qKp6+b1QJ++47AP4ntekEUqII53m6g5j2V9fIXRR2FDaQypurl3YH+BiqW1RpsLEdcmmGnYufBS6tXTO6YVluuo9zNzF1b0rhiikM7XC4xKTH+N0/jfDfyMgSzSsBd7OUidil1qbCcQqM2Cl7Y9yEA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
