apiVersion: v1
kind: Secret
metadata:
  name: authentik-config
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: eehub-infra
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: change-me-authentik-secret-key
  AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
  AUTHENTIK_POSTGRESQL__NAME: authentik
  AUTHENTIK_POSTGRESQL__USER: authentik
  AUTHENTIK_POSTGRESQL__PORT: "5432"
  AUTHENTIK_POSTGRESQL__PASSWORD: change-me-authentik-db-password
  postgres-password: change-me-postgres-admin-password
  password: change-me-authentik-db-password
