---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-aether-api-tunnel-secret
  namespace: default
spec:
  encryptedData:
    TUNNEL_TOKEN: AgByaq9zMFz7P/uXhttqOZX98cjWQedeqBxRG4LN17uYgEdUsw5grqRwvrR7o24Kpu8bgcdeEssxRjVqLlkS4smFaKxP3XjEdtwvsJlR+Tv9ut+STsIW8Z7sUHdy86bOIDtipfutcB6VsPirsFfIO5NvZYaWyyiuk0h/HcIcxABgGvmcmvZ61sPv7jEDfdkrVAXv6rPJfsVC8QEHSMpnuyL+FnB1y7uKHH4bxpYBZfy12wf8FReyJY8Os+ykGOaBIZjghkBm3f9b/yZFJAEuuRAAnVmMOAYwoL19433aZyp6KNPYZfQCL6AIPbDSPOsu3uJzRsfhf9uaCcaMERrZeyBZsg6OTmrryMWNXbFT9NeU7Bjziwcc704fFSETSKldNUYu6NpgzujQuisuHYhJlJOxslr+EUjAxaG95xvp6MS34dXXSf2Q0IsE5MSTWGjSAd9iMpchOcc6UEhGhbBpcMcUuaCvE97dxIy+ZKMQWUnfcQgG2MxjYO33mmGC2E6vob2jPC15csNq2f2AgFS9hMLOBBVbUpHcmHuRB6pUM8vOOiOWk00/yih/hErnwkqx0Sj4hbK8yuqjyuiarVqASKwKSkXbfC46ZdsM/6vLJtKUmoyuBYLWQfRIMYJx7kiXDZiGFRHzXp8ki2GvDyYRrI2mi3jcN1nU6WO42hLkMLi2Ub/3XsfEI6Fhg1AGZVv4RCy9IxDdoLpIV9X6JBlucB4xA5m5rE4+EnRo+2fmfOf6B+XS03Ecc8DEd5giqny6VgN7YE5qwA4tgNb1NtYy+4zM4y4UbJng4elEWzBgw+I4rKIiz6cywQXCzbgrWQqgoGyEkNmhPuLhfrPCKGYAG/4O3OpYrf7Ia9fqd9FD1Bu4YDWt9Eus7eVfegCfk/vZdX7D6YEjmRs/cDYehvZ2DFgRxBOis44ihmlMNXP6YqkkXFu7S0mEvBzf
  template:
    metadata:
      name: cloudflare-aether-api-tunnel-secret
      namespace: default
    type: Opaque
