apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: build-eehub-mingz-top
  namespace: buildbarn
  labels:
    app.kubernetes.io/name: buildbarn-frontend
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: eehub-infra
spec:
  secretName: build-eehub-mingz-top-tls
  dnsNames:
    - build.eehub.mingz.top
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
