apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: buildbarn
  labels:
    app.kubernetes.io/name: buildbarn-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: eehub-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: buildbarn-frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: eehub-infra
    spec:
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
        - name: frontend
          image: ghcr.io/buildbarn/bb-storage:20260326T151518Z-d0c6f26
          args:
            - /config/frontend.jsonnet
          ports:
            - containerPort: 8980
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - mountPath: /config/
              name: configs
              readOnly: true
      volumes:
        - name: configs
          configMap:
            name: buildbarn-config
            items:
              - key: common.libsonnet
                path: common.libsonnet
              - key: frontend.jsonnet
                path: frontend.jsonnet
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: buildbarn
  labels:
    app.kubernetes.io/name: buildbarn-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: eehub-infra
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8980
      protocol: TCP
  selector:
    app: frontend
