apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - storage.yaml
  - scheduler.yaml
  - frontend.yaml
  - certificate.yaml
  - ingressroute.yaml
  - worker.yaml
