apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resin-state
  namespace: proxy
  labels:
    app: resin
    app.kubernetes.io/name: resin
    app.kubernetes.io/component: smart-proxy-gateway
    app.kubernetes.io/part-of: eehub-proxy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-hdd-1replica
  resources:
    requests:
      storage: 10Gi
