---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resin-secret
  namespace: proxy
spec:
  encryptedData:
    RESIN_ADMIN_TOKEN: AgAyYntgIuoONI6kW+HyxBZh9H3EEhO88QCsrE1hjj29pVGZHKcsMUFFElEwlbeAcyuSwAvVlJ3rbNu+gu1n5QTjz4L6WRsHS8r2TTSTCMFURC8jyYndSMC7SmpYhanodNHYnUi8+BnQDxrULOzgjkOdWJt0P7202t/61SA/kXngKc6YL7kfsccsgIOsjxI6cFBoDTtIYkYg8BaPnkKXIO0vTO+J9fZK1RZl39gsWuFMJxuu8CKSvGZ6tlJq8AAdGuZJaQl8Y+KDgXo8QnmHab2JO2DqcBvkzqdtxOW/H/VFzzY89S3AQ09z6HOoCW0m/CraeoMRIUBzdQmylXs6DKWVshOZ0JRSbNBDKuqZZPoCH/bAyD/TQ2mEcIl/Sl4GAMpkeBFRQv2XdvsOtKk16Qyiegk3iahftnu8d9a098LKK1v/E2pcwv/1ET5ROvFnu3B31BuhggLqV3hSe3fwARMaQWOnTnEcU5JiWzbG/ORxr/4i6ITeYKSbU377oBvAuC5KdPQir74DRPgvRn9gdGwpsrHa9LM9bjHyjPzjXeO8XmG3bklAFxje9/QH6mfO5H2sDXDzGM2RoJhR0ZR89XQ7kn5blM/xkj4oUxgcDrnzraX5QTDRxpSq5inhLbQry6FV2YNLIKXGPV5KcJYR06HzCwhGajk4YSL8H27qmQZtBNKcZqPSy3l0CY5OtwQNXLTYuHJP9s4CBcCxw7HvEs3qxT1BnTPK15HRedEzVVvAbkSCJryNeJ893conC/WNHRk=
    RESIN_PROXY_TOKEN: AgAxnNOxz1leJw5wV4w0BhrhHD/oroyqEYSAFomc3PiwBKTGzScAmKIkf/QyUeCAGZ4NL4NrT8mhcc/z7p2lziY7FgIleaVcQWuX/Tqip1H36x+qmBQA8I2/+Hki0cv8nqdTLy3Uw7mgO8qowxngmTx3WLc59RrMYD7SFOXgD3cOXfzmhowRu/uJ/eexSYHV6yqDcKqr7BwNtRm2EJklh0loSFaVFgFxxmSX4FfvZoXoZ7dFOxsoUxQN61Rw9SA5eu9VhKPPvbQVBOoyOxhg05JMIhG5JWGxLip8oFukf7eHPEXRCY25L/z/rh/pQBSCxZma/6BFhcCR/qZ9hDNLjIG+b7RJnSSkFxowrcMN2VIDD0AwBQa0Rx+KoQDOFCiIBro1W/q/Ba8Gf+AbRncu2T6Jg1wg5MK8S44v0wrA0ihPpk0hsktmBQwo05al53LhAR0ZAf0wr36VGYh//QCT5SpGX5yZcqAg3GUMum5Phzmb6H4PJO4vhF6uQx1tJCMwQ3JblVK8VTNqFPIbidcjm04LJhpO0vTsqU5MSLYr9T6YjnpDuxnyuUI4NnWfMpKBnC7KT6iwhU5RE4ObKuBtUJGqxAtLdZb16KqT9lreEhjWzJ5ixWAUUSd79VzkIw6SO4PTr2UFlawnE+bxdDs+hJlH4CVynNAOzGB08hiDs6uItCudKaXI5EdlfbVTmPd6GOJnzOLVU77QQytPyJzIei+++lBaxCv6A2ECTQxGof5LC8dXhVZC8qrT03klKqscAoM=
  template:
    metadata:
      name: resin-secret
      namespace: proxy
    type: Opaque
