global:
  domain: argocd.eehub.local

configs:
  params:
    server.insecure: true

server:
  replicas: 1
  service:
    type: NodePort
    nodePortHttp: 30930
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

repoServer:
  env:
    - name: HTTP_PROXY
      value: http://mihomo-proxy-nodeport.default.svc.cluster.local:7897
    - name: HTTPS_PROXY
      value: http://mihomo-proxy-nodeport.default.svc.cluster.local:7897
    - name: ALL_PROXY
      value: http://mihomo-proxy-nodeport.default.svc.cluster.local:7897
    - name: NO_PROXY
      value: 127.0.0.1,localhost,.svc,.cluster.local,10.10.0.0/16,172.24.0.0/16,172.25.0.0/16
    - name: http_proxy
      value: http://mihomo-proxy-nodeport.default.svc.cluster.local:7897
    - name: https_proxy
      value: http://mihomo-proxy-nodeport.default.svc.cluster.local:7897
    - name: all_proxy
      value: http://mihomo-proxy-nodeport.default.svc.cluster.local:7897
    - name: no_proxy
      value: 127.0.0.1,localhost,.svc,.cluster.local,10.10.0.0/16,172.24.0.0/16,172.25.0.0/16
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

applicationSet:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

dex:
  enabled: false

notifications:
  enabled: false

redis:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
