---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCjqUoSeeLESTWqFRnjoNkTctAR1yTeqTYSUwLOXjvoe9LhhW43I4/QvJIowiRG+Bs1RWTNno2BcCKBUMQ7VGm0sejcS1hy01w6YYCvqQnf96TSrvSPtcrAtxuBaatosbjt/hGOH5NdVXlreOGvtjdcQvY8hLPF5QJN94cDBu6vBoCtAd16ZlEmYabc/t9Zj9Mqrt1Xfex3wqc2AJLd/iA4if7WdLwT2VTsl/1jy2P5OyxQ4lX43nY35v9bL9fehlu5Lb2rA1JoYHThUkQd6rygVBefsSV13eJij0rECcyXy0kN7slWJu37EwXWYd38uK+f2wVHscNwudpBym7KIe7wpxYTIM+F29QB98YZQIpPpl5cOZRsfMXE8ulb0xOxslVmNf/74g3ztdRrrCwJKsHo+Zk/g9UBBlpPyLkjdxL2NbX5Cf/2V89lzCG7kL9cStV5fp2AqFmVoQAiZ3E15kuKRm4l+Ad/zJiskLL+FBC7Kucd5rUFbMZ3f7N713u+3Px0nB7b6zkeHKVeFQnRUjF2T1ETojH7c2dEiyyHyrFHPvG2rQLpIVOHFDCMShEIFxwfiVK3THns9bZ80bqeihkXgVb38t7daNRVMU/X2iHNPe0THB6O1CphIhH45r/oggJJQm3/1rw9SlTylPjn8zttQzP5FYEHkPriqiFqqzrZFSFo7ozHDIBnNPU/K58hFaJssUZISJKCDm1ssBSePFQQP8WGhYdia5m98IDzTLFIHCpf4EkYbofe7zXfIPpswZk=
    MINIO_ROOT_USER: AgA1tfUv70apOiQv0kgbTBYPdiaMWskqcTQ6L4BbNTCo6GAk4jodacd9QLIaHfK0azyplhoJjNzIBaxtmAGkiEchACuSgCbmxbSmRSkKnACCyQVLIoL2k900pbAOsBCNmfaK/S600cqGUVyo2O06Ke1orlMhPN1OegfgfFFiY65lGAk5DM1fGR/dbC0t1s9zdbeSxhGk1kMFX6NDpTuXiZ8T6nr/3Zq1jOlJUlQYHv0XQpa9JOD/SLvvHiPHaRpkPt53eai6e5yW9i4IOXX8VsCMfDDw2NU+P9piol0AZ1x8NOMKL+6ap3qwx5a6kS1IfX0d7SRW8KaXn7V4oh2/gFCzdJKC0VRthaYe658rdvhOW+j9QjBkoo7LgWdxNhXyiv6q5lHdhBn0ubbNbv1ClzNdW2nP8mhpq1+A42WKgFcG6gbrZ6fvyiv7/RGzLTNXTlBPYYNWI8jPsmJyDu+OXjN480nQSMm8axuUyV8W0ATACBU8/yutXYrwdN9nHPVPRdwApMeDtx2KTY3HdJXTEnfqQ936HWgJMkUpRWO9Rd1IxVKi6G75BDJY+qaDVyKC3padGPu/9H7+xe8RwNqsEBEe8Nq4RWUkmVZCZW0A/ABMtGkq8O1LV0/+X0pVj15kFUDpIMQkt+DS31V+UU0WNP8LrEj1573Hb8xb3hazzl/f/pybHtJXtuSgh2l9uuUHG2PkJHNHjDti8aw8VQ==
  template:
    metadata:
      name: minio-secret
      namespace: minio
    type: Opaque
