apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anyrouter-check-in-once
  namespace: ai-services
spec:
  encryptedData:
    email: AgAWOtbWXcF7pB1z6lRT0cPC1a3b1WsdYOHk6VBarWilDCVdgDhUAm+XErkW18TvzDucwLRxnMaCWAl3rkjI9AhAVJ0JXmtVo0ToCoYDifx+g1JID5oCTtRMgGxaqiPROqoda4U+CTuLYh+XFe1QgxmjIgbSJ2Jw4XmghztMTlD3UmM4Mi8Txcm1wCzNkh3NifrB7FD+K0d4k7Zuny5Oy1ePZiHcY16gr0BPoXTv0TvMvIZSlG6IJzxxp/J/gbPlcN3f3vir70mrcnCcZo3v6+/ib8WadOsDKQ2sbfkYDI/Cz0TJuncGOZzPC6+qnQ9MiMrBCeHyO4akF/6AtB5pSIqQ6z5OciX0/mlxCeiUmX64TYJ0Od0BQQyltvyuQV6w4m86NuINGPbZ1aqeM/9yQJv2YNNbPGjI34O/fSkWHNDPYS5NbvAgujA1Lujcv9fw5wer4mukdJxgxoMvoz9N+yN7x2h0WKfsdpiABQK8cqGm6/qDwUE8d645NreWgyM0nAaTxJ+05sbxLzxLY/FB62f56DqP4SoAkLFhkdMA9Sn7gnbJTtPxCh//8a8z0pczWN8F9HDTE4GmICSWJecoNHsbioV/ctCJTmu4PVeLKzso09Fcpa8JfC3kLtOB94+35wJcSwlyKxXX3MZWX7uQWsl43Ijl+Rx/rwbIoLZXMJCj1eaEei6XmHvc5dgpAF1L715Hpyz6rPZjswB4vGeIg8clRprT6HebvFp9BikyVQ==
    password: AgCynWpTySbmUdf4qpaseJS+S7/x5+FHHBLvu21m29agrB8o/MX/amWupLvdNnmbofL1uoqrmforbvpS+6xlK4rtVdCV2VpOkRjFui9YX8nV4XHwhA6fadCwsjGqEywKg83jDBP3qJqbPCIl0DlS6GmzQIalYA4iLAONlEhHkY3n/zwWmu425qiEqx4r0J9jWGwgXnnP9zQ7TJMdRkBNK0IOKEZ4LZTv47t7B89I+uPHCvivz06I4jp29wf3MclJa+MRPL1A8y4ZFdT1j8i9TfMesq1xGdbKh/qNtLmMMmzDA6WuBk4ROe35R0a0y0+GUa8RQJQ8nTyBWqe42U95I7Jo4/6PRemlqU99WFHNeyAOQ/wrpqCACBySCrsuERI9FZbQLKroxdP8/2JB2sVTKjIpCw0DBeMupoa1vY14oESBPvI/mhF8mEvO1BIOkL7Iu9t9J752cC8uBv7DCDidx2jmAliLoBT8rlpE39gRWMDnTbhMkyL/180XbJL9riroIA+R63QV5dZdL6EAl+1Y/LmJE8zsjfhEHSF4RHd8sEifmjZ8S2ADow4PGrv6YF3/ET46sxsGaa6FnXbdtghWeAnEAFPFSo6/2/gBEb/3kAKuFNgxj6tZExs+nw00DxCQ3OcO02Z5aUkZwEqNJNOFoscs3C2wh8D+tQeM32wqVd4R9417rpJdk4LOB3oDYpltLe5RDHfkjH90Xdl2
  template:
    metadata:
      name: anyrouter-check-in-once
      namespace: ai-services
    type: Opaque
    immutable: true
