apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anyrouter-check-in-once
  namespace: ai-services
spec:
  encryptedData:
    email: AgB97USEiOdKKZLKcaeT1DiIq3jJRnZo5qA0hexQXna9MK8qL5ockyIN2/fLm/j1AOh8xx9npxWHRCPz3Jw5eUfcbNY4VFS1whQKMDLsoM/HSiNAYXyFgsAMv/AplDk6FOZMx3zqzT9VtS7QJyQXv3K93MF3cGklkXHsSk/t60PupGlBq4TuLGAG4Of17AJKalhrvXXluPEo24rW4Bh5nt1L6YPAZgTgtljE/F7SQdtUXRtBRb4SyGp2LwX4ztVZx3s9C4omTfzFK5Ckdyt4dx/zTHM8aCRTW9SQeCltR9xUEM1wIXPCdYJB1gEbgOglmYZDYDyzbgV5svfJ+JK3eGoBVBBmXcLjPU8g1ksY1pOc9RjTver6gasYMJS5YCp6CGT2ZsWWGnOS+MRATicApl9EODxCARgg3YX8rXptINTktACL5Y9CsEt3UGRlCegYDG/9Ch56mX//XMYvrNIKiKd/QJioDRLrlxUaKCFKTmJOiDwzw5CrVpSVXUjZ8waG427ZSW41z7kSm3gcRlndOw86S26MCqu+CabB0dWwdkPBy5LAnl1vxI7wzKPJ9owHBB5urTk/Eu6aRH3oBY77mP2PPAT5SUR1q7WBHloN/gV++sNB1T0T1g/q5p3dZFFzgv54Wmbq/knu/vi0yYWDW/Om7zlcy6XDnnsg71/1GYX0Yd0n6cClN50FaBGpQwNd51JdgsHu68JTz2cfdUQ1zLF8nlK8G9XLVVnPGn5jWQ==
    password: AgComHgiJE/w3+zIsjd+mP9sLNHIP4t7hdhW6RknoYY6mJsY7WpbHO430866kEYA56SKhyUmSpAPf9nt4iRhQl7pisAueylmElLsTlnBZpFQ6p7zievMSujzbZSVcdsamJzt/Zhx7qFd6is1nr1tsR/2ujuySeWLWKR16imtIR6UOOd8dd+ggBq+g0OvRoWkYljxmdXZFfs581QVbVD3qSKQKFaKsJflEi411IuDnqg1BUWf/mMhJfvMlFy9mRmBgnWddlWSB9rWE2MSxk4Tp/mxvKesqs7uDtj6wATA4H5WEI5V+z5YI39lZFtclJQaDPtP8ub5Iy8Z/0SNIj0eizcRvGE59mI4TbduMMhP96ljm2dGKIbdYOR9asKnWsM/UjCrHRIK36AcscvUeiNkDD8oEDpEO3AiCc3IClrnfcMhUPqHFFRtE8P4K5U/lLLEdhe9kAvIICdde7GrBUJOAwROPqfxiMLS0QwOYMYO5/CVskdvwiHimENUOEonj03MvjqyWo5rwTZypZ38oYKrdsjoqojWlnVsOD4EVrqR9W924i4JR03TceHpWeGg8qA61xsIKLciaSLGbGfbjjwUMnEzLF1pGDQoSvKm2XqGOx3Hqw0UPokoO5nhwljz87jcedIGWuQvi9zBbZ8tIdHUndEiNS0WKdlnJRjnhi/wkLeKQiyjG2f216Vt3fdYnhOW1YqOjj2JC09MTviN
  template:
    metadata:
      name: anyrouter-check-in-once
      namespace: ai-services
    type: Opaque
    immutable: true
