apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anyrouter-check-in-once
  namespace: ai-services
spec:
  encryptedData:
    email: AgCtm4bAZnfdHkFaOptEd7nBGSxNe4Jj/wBmS3HmcO7XPGeAnStPyz3jnZtvclNdv+Bg2l9OhmJl+AOeE68CS3fL5Tg8zgWyyoonTSVF6NdVR7MjdjLV1d+PurEjZPUsrCBM4SekCOXWVzhBY3HOxglyDepyQcpMaHU148QCf/+Sg2QLYnMa88QHuEAwbiHuoeLT1uHUefiLn7wCuR+plEZvv+MAJH4OPHbWPMBpyYh2sfaJZS0fqkVZdRK3mOeQ5xMwD+wrPXs2lbwnJ3ZTrUNJb770jL8gy5xAKSUhCgsC3dGtkT6VXsbqq88mmzH54+pmvUkTzgcaodOQSMwLN50UqzdoJa6WnI8w67QrdjN5RBsvuZVV7A5oMN4K+2cn1kyWJsdaRK78L7yvbtFaUhQFa1UeH7inpgER7TfCSQPpevxVWmZz82uGvfnH2+oBWwUkvU8O4txMWJIaTkOiBP5A0dS4f/qYbx3FTlOFFMdyM86DCBIVhvVRdAiwSxhILBbICnmlbUfHl32NT0Y17oofoin0oF3hXtcmzdRBWP+UpabKSi5z0jf1+B0oRdk6OdJctI5mtLSzDDGOxh+E1wxssi1LcCY1Ned1fFex72+NEOzFlzhnQ8+HWPqTs6vXQ5EcRrSxqSMgcRrMM1IsceESh3XJWj/wI6lV5ashqK7+cehpFxhl+CiSoevAHr6DCuBxZjLCJc+RzuBw6PuJnfCftIAS4P2JHXW2bIj83Q==
    password: AgCcazr7TcI789VOk0BKZx+Uv5FEDYgxxmCQaQwDBZkwAumSPpaTFHnqLhWLZuXFC3tlFokN3vPgJC/L20PqS/yKoA9HLut8JcseTHgF2cEfRIX+sSYaLx/S5OImKUX0shVZAcp8J/5mzUVRxTIfoRTb6afjT+BTme7heQcl4lPssUM18S0SY7WrXTy+0OQ7g3kcN8Of+q3FK4YpjJ4NkOEwR/ZkUImUGDCzrrXxtC7uXzn2jJ037IuE5LgGr7IUDKFbZT7paYEsA8Sy2fuYG9rbWfLNTw0RRFKJivXZIn4SiRuDd2nnfv7Ni6b6bxTumpepnj3BqG7eqfyeBf+ezvP4SNglAumpHokF1AAMnobgRhvcDnehUNp89M+1F/1lcgAoVzgCOkXa1yotEDW9KTtWq4UCmjn5Dy44cvEexAs3fcp7e71tXJwkXRWzhkdnmWJGssBvEMxaS4M8PgNPJuStSDPyO10zkZZmx7Ay7WHyhjShuaicus9Np/Pmgvaox2x5xW+rZ44uYWbGNOwTDQ0uGHFGzgVMY0nzVZTUUjbwP3ZBZjC0ol51AEwotmoyBj8fG+MjIOiYZFL/DckRHiYDEzv9U+2nwgfc/IiLqWYTC2ZNx+pu/k2SloabVcly2YA+/uI9KhL3rfzr6DMwwURTTRo7GRLsyx6jtoVU7mP/ITwCSCIGajgP5D3iuB3z8H8dBEpGDZ7h2n7Q
  template:
    metadata:
      name: anyrouter-check-in-once
      namespace: ai-services
    type: Opaque
    immutable: true
