apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-services-backup
  namespace: ai-services
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    app.kubernetes.io/name: ai-services-backup
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: eehub-ai-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-hdd-1replica
  resources:
    requests:
      storage: 20Gi
