fullnameOverride: sealed-secrets-controller

image:
  pullPolicy: Always

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: true

rbac:
  create: true

crd:
  create: true

metrics:
  serviceMonitor:
    enabled: false
