apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-app.yaml
  - authentik-app.yaml
  - ../../infrastructure/longhorn/base
  - ../../infrastructure/cert-manager/base
  - ../../infrastructure/authentik/base
  - ../../infrastructure/mihomo/base
  - ../../apps/cloudflare-ddns/base
  - ../../apps/ai-services/base
  - ../../apps/inventree/base
