apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns-config
  namespace: default
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/part-of: eehub-infra
data:
  DOMAINS: "master1.eehub.mingz.top,*.eehub.mingz.top,ai.eehub.mingz.top,metaapi.eehub.mingz.top,mihomoui.eehub.mingz.top"
  PROXIED: "false"
  IP_VERSION: "4"
  IP4_PROVIDER: "local"
  IP4_LOCAL_INTERFACE: "eth0"
