---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-ddns-secret
  namespace: default
spec:
  encryptedData:
    CF_API_TOKEN: AgAW7bEtTNXdddt7KIPaXjeRDlR7qSOQ3vhjiOszWkorgR6dbbY090nSxZxMTpubq2ktIkobJZaLGikvYvR6yj+r0Md4b6qIHi97f3T8apCsDzY/3XNmhJMLG3j8SbXpLylqu3RfKsdmyj1GmdzIBcUfJ/jxzb7xaNe4VdhKV17cxgl5dFyQ1A0y4XjClKSjbN3ph1Xe9esrL6ba/3q50tGXMVwd2Hk6CwOi6M4Ob8kxecaRWOCQ5ku71LVJDxo2AB0auQu6rKcZsWqVRxlW6m7WA/d1SeKxjpEr8OodiCHxumtypCQgXNq221srJDP+OE5jrR3lTXeIhvOXygvkZnoQWkGFfvpmzkGWoK0r3ZgzcG8kux4vRjfkdsclbk3R3AqVuQfcTBpnRbWDvQjtYK6Gw1d5D5yKkRnKWEAHEZbpt9tZsB25gPiNa2T1/i6pZfnKFmiB8dBDqP6p4gUE42yvZxTSJUXACx4cItvYeJKJ5tcYDWc5RzUFefnHGapKTGnBEtK7Wg/RSVxZ+sT4sgS5AfMIYsNhdD/GKYD0vRYKlMQHBJsFUmsBCYOaEk58Z0qbjNg0/Sb5kzdLbfYmeFhP681mFVP+H+Xvanw0x4/UCUlgSseFhYWoBIb4jxFejInOCyMsx+7rMGg/etxakwI1Owi+ATu5976bUpynjOo9R+dc5+vsGK81Do6mfU0onZVfkxPlohQ8SHNaAmySGBTSYipEHXD6JKWMntXJcRiK+PB47Jd7Xrr8paQT5qpYstyzucWA2A==
    ZONE_ID: AgCnwW3UVIMhw4UXVHGEIIy+J3jiRGpYlbtfnVtWac63whfBpq/hH4ZDZOUJn8iyVmulYJH5HDGCS8CafZCDvCBVHyzPQk+guSqGHy3DCthV3h8KJpx+I6qKLCLHIgrpnulczvdqIW5309fFZzQUu6DiEld1vhJsyOzcq82t27GJn00VW3J/spool80+RociVG/E+v8BlKNo4MzjKxkhCIADCoHh7VlSGM/fKfxIiUw71rY/pZ8gjrnIAIunUSA41lXkTjqhU2Ln3aQD9RFGOeQybFriJKB6BtB9BJM9XgiiuKgik66pSW9YJhOyb6YVD+rLg2Ls/FX1+jUi2YNeUuO4kKdv4SmCLwISvXtUH22DdE/T16cn4MQlMdAqlntK8BDwlRPUKeqcf0R13RGdJ++HY1fRLJJaZOLjUe8WL3dE4pUMCJvcgRwjz3+auo6wJLYx8h6b3bkq6YESlx4GoeTl+tc5NFlsXPL61Kae6+dlB1Oqon3K6rXdYqNgRVwgdght8ESyNTZGJPRWtahH7JtUyqoIdfPCF/sKJp/LFMl/wfORs4ig7MrVUa0jEz9AoPyEwUkZ+kz1CpBcN5j97p7GP4j2xg/V3hWxHAVOH5lEak957tnQVyo7wp/EGE+7CAYtfLhOWVbgpVmc2ZlvJpOls7frzQ8tdXw8onqMTT2EXmDNDPu1sDT51Oq1svmdQpibvKUf+d/6+lGirYW2sxnZdqy2eNTSQXeq/tT36a+Hlg==
  template:
    metadata:
      name: cloudflare-ddns-secret
      namespace: default
    type: Opaque
