apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sccache-scheduler
  namespace: sccache
  labels:
    app.kubernetes.io/name: sccache-scheduler
    app.kubernetes.io/component: scheduler-ingress
    app.kubernetes.io/part-of: eehub-infra
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - secretName: sccache-eehub-mingz-top-tls
      hosts:
        - sccache.eehub.mingz.top
  rules:
    - host: sccache.eehub.mingz.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sccache-scheduler
                port:
                  number: 10600
