---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sccache-s3-credentials
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCUPzvEoLvOs+UqZKMvuLKWWNikwdzux8EcW9AJPArVjglcDn3/00iLzFFgn0Eb67uD1m81pzifBD2duhjWb/aUJ9c0ox3EeK5zYWC5c2tDKPi7DHVc2FkkBA3C/pge07jWFqW5BbRgqSVHB4ZWwgMHR5efYoVCdMnZWdL89SlYlgazcMSEzORDWRLiP+IZHkeRMNJFmLg6nLYJKofZz03dKuX1RjJ0yXBhLyOA6H7RQljNFg1ZKz8HBDcWxbhDlMUqmafYL2Po0cKZuY8HsbwDb37K/EwR9R0Vmu1hHtlrFbKLN4fw1PcVUxy4yNGyf/mGFnKpZhPDnKX8tLhReLKPGzGWFJG2y8s2HwtC2TLZXnZCkPvUp5bO44dpzCjwOt1Oh9pc19KCZW6ccxf6OTQ3jbjv/S8SFvDvAzU9Pub4Z0ngbQcAFtckn+nTSmpO30h85+qfub7IfiPDKIsig4zyrmJawxOgrJr/hk/26ka2l1psH6hit8oKCbtq28tby0YeXO5bPbj9QaZEh3Y+HvJJbWxrk8Jjblr+s99XST6w6mBiR2d6+iQv0EzqIeuXAtNnI9kbnO2iUS/U4I6fVR2Tkro4Dzni29nuBgcxH10DjUzEluYQ52w5uQOiWjaf35xD5mUkAdPRV3+aOg0wqiyb4/TO0L+0zQXkIykUJwrOnu4/1gsdJTm+8ldZafmbfLK0szETIsMyUjVN5CyLnA==
    AWS_SECRET_ACCESS_KEY: AgB1qEYOx2I10z37T2B5smTQ65nyYKdsFyePv/2dwdDgT7sEFKqPTkU3Lhoso6GpHpNavuofZT3DKuEHISBHXKf32P1g3+5rhqUs6RiQ/eWDBp6eJEoHrxEvLL8QVjO8lxEDlRzyb9PUpxBRmqr4jxKxDwncLvwtz/aQFda0/SbqTfEHSAmqJqK4q8ohkUm5bHYnpB+BfF33r/E5gy4w6hRaVAuAXcZiRVH5If8LtD/h/Jbq4x4Hhp7VAW90dMKLYoryd8zqeJYCunpJLkEjyBSTApi96bx9fsJ+MwSm8zP4MLvLsYR7kI55VAuTcgdelNxOOa7pkxySgI5jnhMF3pqb7c3SQwQ5yoFOESXuCG9DEN9zXiVBIMDMYcLGCLxwwMZuHam1xtCa6rJXNBDGFCK6si4GSnUHu2LqlEPEvDQUR+zeFI/15P8zxl6CIouWYYjgjRNl6pWrptYfXvaW6XakTJxV+2TpYoAG4wsiwylf1dPn7+/fPi/x78Kbm8p7AvHnsLooLva6HDTjCiodfbZ/3pt0S1zRAWGNHjvKK1Rz3S+g9fRG7g6AVYViRKbvw36dxduom3M0IJV+Ez9q3lpKt0uKC79JAqeyUbH1eSRJF1zEwY8Qw0tbCFN7EdXph1iAT1GBCNqGdPqWZcv+xEZh2X4olQhw/B2InLvfYYga0K3VteCoQFljQHokf0cMqYsydoKsjTN0097RWC4eUZVSOmxWaJLoEtfLsrsMHcKydRYhyo4vVFpZ1Owhkeds0xY=
  template:
    metadata:
      name: sccache-s3-credentials
      namespace: minio
    type: Opaque
