apiVersion: v1
kind: Secret
metadata:
  name: sccache-s3-credentials
  namespace: minio
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: sccache-client
  AWS_SECRET_ACCESS_KEY: change-me-sccache-s3-secret
