---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sccache-secret
  namespace: sccache
spec:
  encryptedData:
    SCCACHE_CLIENT_TOKEN: AgBMGvq9638Mftu63La8CZZpY4jPeJ5Zh4jA5bRljwkJspK/rJeWjYSoC0bjwcr1OagWrELUf+LIyV6O4ZWrFBsE3z1gdfAzTgWxS0fL30RTaRNq9lkSEB088Dc/mw1EiPBGV9DpmAD6z/nWCTRkY60r/E/qAtJWjfT8ryctLf4lLwqjgh3QCA1PHsTYiIe4sI/Tihx5pUnd4AfPW0Ob+yYfA6lnZz14tTuPng6REYMwFmbQLAqtwcRiM+yYcOFQ6b6cOZ/918YcTXEqWVfFC3NPGTJYBbtt46H3Mg80+JTT/YBTqILLi/XI0w3sAs0CDY2hg2AyGlaIccM/bhfSKqfUBe723x2hGTZWKiHJYkPVHBJY7JTs03/IjJCIZ3ZvQ3uUYmJq1y+Cuuzqdq2nobdHxvO009olzLOU7lSbU6S+pW2IWca7BL7kPT0bxrRY6Bi99Wx87dRAKhlTTApLcEpaHjfaNtGsWUsOqk+9kvvbcWVyy5ezUR1oeT4wb3N8w4OcQDYDpfYXFzMeFhBvgqoYplTE0/502isJIdSx6ijuoUqBLj86gPGuKyM5nIn+4fKxnYn/ANm7zDJLy3ndu5hB0TT/IRV0HAb3hdkN7bEd/iQ1E6knZ25cv42fTv1HypJB2Z0brugP9G7c+uHLMUk/HFtgXCfkNATACzvL/L0WIZ4NMhgP91WEjiNBqlzwFTboGYEb0pB4oarfwmzpcQ+1GoOLLbz5dqis3ZxhAq7fRWDMIhA6OEPwNtJAz/J/+HvKGzSReEehgeAq0RzW8nIg
    SCCACHE_SCHEDULER_SECRET_KEY: AgA8dz1zEAI5UYaDFnYDbobzzpvAsYbvU+J97ifsYKVno3bASI4hy8e1N9mbBZpO3is0aWYtzc+db5A/8Wx+rw8VjKdFfmIIcBYZftSRKRzaziGRBkTGWQlwG5lcXhgUUisqRSDrbqaTidGhKm+wSEcREji6j5NVZPlUTTunHko0oRbUVx1VK/NpDS3LhoXDxuHCjLuHx8yMnFkXfWxV/gIe026mQDH+JJT9X/aFrImKsHxrGrgj4mVfDOcyYbe3spSvCyTqmS+DftfifVGBAdc6MhS46cZw4VtOj74tpUpmo+3ho6CR5Z1hyaTMYFLn/tdu6nm/AKb/ThdEpMiet9I8gCunvpA8jmGfkRvLCBY/txn3dBylNxUeFoO8ntnUQDjKIPxuA1oD7NafCP12z06Du7bS8KvycWDBJdGTSyn2xkarPuuJFbvQ/6zCuNxh3MwEM+6fsWNVBe4maA+phfiqVNkg2v3TEvIlLe9dcxhkzltZDcNvlv9k5QPZOEiJlgJZjQgosve6TQcrj99pIidY/86dV3MGmct2u4SLwVlSffBq75y8CFjkZm39goc6cF1x/mIj1PTlFiq+zWleEeQO5g4Unv6Bq478DdMp80/IA6CeNhkTfDkbMDmwCXmV59KdilNOFn6OQXvNrBlbKzHUuU75f2NxmMJ2lE4mHjIENeaRqS50L2AZueaCeLSgANf1QrDKnvWNfn2U0fzknl5zUShj+JAcdKxJMYZZwoEYw2PH9jKYFntGXFO5agR/eMcjWSsPyaxolHD5uawzp9bp
  template:
    metadata:
      name: sccache-secret
      namespace: sccache
    type: Opaque
