---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sccache-secret
  namespace: sccache
spec:
  encryptedData:
    SCCACHE_CLIENT_TOKEN: AgBbTcnXMZS5A6zFQzzhQkTBrvuorNqGUuY1IwQgaBFXNimINvW0EV0Y4eYFsbqJ+wr5jzmb4RouZTA77SQ0WE2DIqNILF+820JIDgyZB/LeDKFlxNPVSfQ7Hcj8h/9/RefSze16a9qWFsjjForRwNYGVyjnZVsJoVGEV5Zj9sG6vurUMVfPpZHAkeOwbXVsX82bbg+SlOLTWz1A+DEhyFyEmdpFuD96I9e43HYuTA1F0B7576L9N4akn69G1ohdtrKMHj4L9WlUCBwFoSErcn+h+ykv97sVz62jb/2/EF/yPuLw8d3en9F1FTugfYPAeEGEmCLGluVbXGtZ79DnHHYCAX+1tC330zpCkpeaVpN77B4ZX30kwcDKadyEOdsGMcPOeYKewMbhOH+eTE+OzPDpA5qcHoajnCzZnYziEMKDHPOIDHYj9by1Lr6n8XNfVa3dWpT+zZaeT83C8ZUvuolUkRbNm7VA3+qhmAV1FmSUcjsEBE7uidyafM0ik0+2/+Hnlu4oRwYaGqK3YCAa7RTGx0qzsantnHEnK/p/3O29uIbTrKavJoc7ovSxSn0nwcSoLltwu+Cx9bDZ7UPbomx0uYA/JTBgI3u/oLqbAFCCtVtdXmNAT97Gz4KL4cCF8oey4za52cdNgR15WbyLkpqoD7fWQkBroS6iFJKNujqfbBP6UD/AcOTJROj+48AZ4CX+98ziuMJ3BUW5jiw0Ypnh8KbLkFxyEYepWC+giI8RWMrg2Z6CXkav+IaYrfTutyV9NCR623AuPXKVCFYuVboo
    SCCACHE_SCHEDULER_SECRET_KEY: AgCCRYqldb4BoyxpWnNXH/w7bYO7c80mweVLzU4P8mQKIZ+fxqmQb5VM94aLdA3SC+97yDn4EVUJ1LkXmlmqu6rejPnuATBFq3oXCvtDmt+/ZeWScpj+GUzae42/Ho3Np+r7Z9PRarH5evHW7EJZbBcqeJl7LJu1NxZ95LPdkSfBVbS9YAX5xqF0h2owreH6SLG3dgf2j/H97vruBrAL+pb8HrlYdMfgq0n3NYmVsv3D2lAj/KA22Sb3mSACBeX45NgsJkNUjJyE6SGB00sd4B6R7qrfVlcn6vERKiVYQcOxCaAyZ4UEe7+kz7EsLnEmDaHCRNrYby2TjTgOXd+JzvoT23yiTQ3g8Mm7Zd6w3+1mLump8dDOLJPdHWQVWXNYsRe062hJkI6L5f33T6S5zI9nO2nO9a7PWzwdkbQJiN7chLo7H2guiPuHi9V9i0uyQ22b+qDiqtsfzvU3A8j4hYJ3fWF7Yzd+M6PKRVIjDqmBm2WX2Z4+t8nz/OGp5PfQC2glhcXVFjkN+7z9u3Txc9F16a6Y4Ium0mSITlY7LBSjDLvui2OPL+DGY4Xhi/Ycte/ZVE7JTyC4kh2tyr/dZjqE1qYOjO4942ncdYoBPRWAlJxLZ61gPDpGzVQIilwiIc616OK3gXI3e3etbXi2p3AgSO1OiWYr4sjR96IK/vDfNTBZahC2568E4721hifppDeArdzDHmh33NtFQAvZJJCw81KtyXfDkTELtfR10z7U93h9jn7JuFivcSMI
  template:
    metadata:
      name: sccache-secret
      namespace: sccache
    type: Opaque
