apiVersion: v1
kind: Secret
metadata:
  name: sccache-secret
  namespace: sccache
type: Opaque
stringData:
  SCCACHE_CLIENT_TOKEN: change-me-sccache-client-token
  SCCACHE_SCHEDULER_SECRET_KEY: change-me-sccache-scheduler-secret-key
