---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sccache-secret
  namespace: sccache
spec:
  encryptedData:
    SCCACHE_CLIENT_TOKEN: AgAbt5cOyqD+IKV16PPo6MPMdbW3FAq+9zlmFqBcF6CjTL1Mg3j24tyqSE9g7ZltxO6YKttOpV99uLNoEq+qGNQOihLC0TxO7DG4iDQL/OJ+ZbZzg297m7x8GIyO15e+Mc+dj+IBtoupdfswtmJ5ZIjZrrUFqbn78xlayE5CROWdkTKQUCOPV6NAINPDYZkITMuMcOpiYp5LqFhnqr/ebZIG3DM6eHJy128It3PQU1Tb3qUiGCnPhUvx0q6fcIcFYeNwHMZaq+YBsz2lHmmUmYjUUQ4j3EfpK0oSFNVJ8zRdau489MCGp9bOdQ4f4NTlT/hkArIkx5wkuvBfyfrBefloOZ954aqp94Wk0Adwl7oNce7/pfH+URx7iO+CvO8OCiMwMdb0O49wpG6qykyv2Bft8aA4vT0KsOA46nICogSku56KqrV3TpqXsRCALxLGUh1jwawOCY7sOMkc3du1b+ci1pU5EaewdBZ4KNxo26Xc9G0CLEW5I70wmFjV8H+RySU9CefXH6E0gnbgqRwdEOSw7zelz1W+TdjyA65Gsivph3IirIRy3C8SEaYAl7oJgqjVjcFQWT5gdyvdhXJiUr6hqJ/46NiaUE7WUnL2Y+WiJkBAkm7wCyehldIyplSTG1X7I8TFBYDv2AlJroOKj1I6+QlZ0Gq3f87jJuv5l4NQBdrHp5K//d8lzfaon1XihUUprUmW/gDNcPHzQ9Qg5Prx1X70Y34LkpPofapcG4hKE9c324KfLOKqvLW6aqXLVthGAx3gQS2pzCA+gVyc5qeN
    SCCACHE_SCHEDULER_SECRET_KEY: AgAj4SBtshSPAKeJNNJfypqO9Hg9XW0jBi8UWt9vDQh4gWOwII+PxHhdUv3c2WdQNpQy+++GtraIQvLYfmmO0+8AIc1vMeLSwXoI+w31KGU5PAuxEB1NjW1iopIXHZyBjfr9zYuLoxaVWApdrQ2uE8SUTTPv6YGhi+mk+L58IIj3JzUAx3PNvoHduRbkfACTOyiOAamjrM8lrsSW3nRc/a7YmpMfUklvYPbWLac2qV1XLio80HKB3C9iON9d13nAWkAIvh5pe+PMT35XQGryXG0xWDVxjl10tV4eZjpwFgJFuShtfy2CdELV9uUymew560d9y+NEWIFDVm9LtJ0LNlt0oP0NQ9M07b7nNtKmazhfOrxMZ6ZvwRfTF5yD5kR3UJeqG/+b6tN+pqUh3pHEZ02JMkTYrdvObXW/M/gMW2c5uJOF9+RJFzHQsLAvXVWG82A/bCjN1hViXnx0aSI3y+Up1Kl8VzppQWP42GqqXM0i1GMttcjcb0Vvm/kGK0O2mPQ0OTYT1Qr+d8BUeVv04B5ltTEGffFs2xcSf38p+CHt+coDhxPR/q2nBDeI4zGXm1M35Pkejl0F/pVvvk4woeaQvLUBmccmxUVzZ9uikYZ4KkwUKf1Yt9NRn9WiIWbj3+CrrkfN9uYmAdWkiTrW/2CgKM+yVv8QXfmEaiGpzY42hAMW26X1TG4gYA+zdDRWl+y3DYU0sG7osSKO+X5fiii+fRh40+6InrcNanSUqLvXFQMANz7/5w/TCEfI
  template:
    metadata:
      name: sccache-secret
      namespace: sccache
    type: Opaque
